/** Simple picture stand-ins until R2 artwork is ready. */
export const VOWEL_WORD_EMOJI: Record<string, string> = {
  cat: '🐱',
  bat: '🦇',
  hat: '🎩',
  map: '🗺️',
  bag: '👜',
  jam: '🫙',
  pan: '🍳',
  tap: '🚰',
  van: '🚐',
  mad: '😠',
  bed: '🛏️',
  red: '🔴',
  hen: '🐔',
  pen: '🖊️',
  ten: '🔟',
  jet: '✈️',
  net: '🥅',
  wet: '💧',
  leg: '🦵',
  pet: '🐶',
  sit: '🪑',
  big: '🐘',
  pig: '🐷',
  dig: '⛏️',
  win: '🏆',
  lip: '👄',
  kid: '🧒',
  pin: '📌',
  six: '6️⃣',
  mix: '🧪',
  hop: '🐰',
  top: '🔝',
  dog: '🐕',
  log: '🪵',
  hot: '🔥',
  pot: '🪴',
  box: '📦',
  fox: '🦊',
  mop: '🧹',
  job: '💼',
  sun: '☀️',
  run: '🏃',
  bun: '🍞',
  cup: '☕',
  bus: '🚌',
  hug: '🤗',
  mud: '🟤',
  tub: '🛁',
  gum: '🍬',
  pup: '🐶',
}

export function emojiForWord(word: string): string {
  return VOWEL_WORD_EMOJI[word.toLowerCase()] ?? '🔤'
}
